;;; haskell-emacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from haskell-emacs.el

(autoload 'haskell-emacs-help "haskell-emacs" "\
Display the documentation for haskell-emacs." t)
(autoload 'haskell-emacs-init "haskell-emacs" "\
Initialize haskell FFI or reload it to reflect changed functions.

When ARG, force installation dialog.
Call `haskell-emacs-help' to read the documentation.

(fn &optional ARG)" t)
(register-definition-prefixes "haskell-emacs" '("haskell-emacs-"))

;;; End of scraped data

(provide 'haskell-emacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; haskell-emacs-autoloads.el ends here
