;;; lyrics-fetcher-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lyrics-fetcher.el

(autoload 'lyrics-fetcher-show-lyrics "lyrics-fetcher" "\
Show lyrics for TRACK.

TRACK can be either a string or an EMMS alist.  If TRACK is not
set, for instance when called interactively, then
`lyrics-fetcher-current-track-method' will be used to get the
current playing track.

By default, opens already saved lyrics file if one exists,
otherwise performs fetch according to
`lyrics-fetcher-current-track-method'.  The resulting file will be
saved with a name from `lyrics-fetcher-format-file-name-method'.

Resulting lyric files are saved to the
`lyrics-fetcher-lyrics-folder' and have the
`lyrics-fetcher-lyrics-file-extension' extension

If SUPPRESS-OPEN is non-nil, don't pop up a window with lyrics.  This
is useful when performing a mass fetch.

If SUPPRESS-SWITCH is non-nil, create a buffer with lyrics but
don't switch to it.

If CALLBACK is non-nil, call it with the resulting filename.

If called with \\[universal-argument] or FORCE-FETCH is non-nil, then
always refetch the lyrics text.

If called with \\[universal-argument] \\[universal-argument] or SYNC
is non-nil, then ask the user to select a matching song.  This may be
useful if there are multiple tracks with similar names, and the top
one isn’t the one required.

If called with \\[universal-argument] \\[universal-argument]
\\[universal-argument] or EDIT is non-nil, edit the search query
in minibuffer before sending.  This is helpful when there is
extra information in the song title which prevents the API from
finding the song.

(fn &optional TRACK &key SUPPRESS-OPEN SUPPRESS-SWITCH CALLBACK FORCE-FETCH SYNC EDIT)" t)
(autoload 'lyrics-fetcher-show-lyrics-query "lyrics-fetcher" "\
Fetch lyrics from a text QUERY.

QUERY should contain everything required to locate the song,
e.g. \"Queen Show Must Go On\".

See `lyrics-fetcher-show-lyrics' for behavior.

(fn QUERY)" t)
(autoload 'lyrics-fetcher-use-backend "lyrics-fetcher" "\
Select a backend to use with lyrics-fetcher.

BACKEND is a symbol that corresponds to the required backend.  As of
now, the supported ones are:
- `genius'
- `neteasecloud'

`genius' fetches lyrics in a text format, more suitable for
viewing in a text buffer.

`neteasecloud' fetches in the LRC format, which contains
timestamps for every line in the lyric text.  This function also
sets up EMMS variables so that the default
`emms-lyrics-find-lyric-function' could find lyrics.

(fn BACKEND)" t)
(autoload 'lyrics-fetcher-emms-browser-show-at-point "lyrics-fetcher" "\
Fetch data for the current point in the EMMS browser.

If the point contains just one song, it will be fetched the usual way
via `lyrics-fetcher-show-lyrics'.  Lyrics will be shown upon successful
completion.

If the point contains many songs (e.g. it's an album), the lyrics
will be fetched consequentially for every song.  The process stops at
the first failure.

The behavior of the function is modified by \\[universal-argument]
the same way as `lyrics-fetcher-show-lyrics'." t)
(autoload 'lyrics-fetcher-emms-browser-fetch-covers-at-point "lyrics-fetcher" "\
Fetch album covers for the current point in the EMMS browser.

If the point contains multiple albums, the covers will be fetched
consequentially for each album.  The process stops at the first
failure.

Requires imagemagick's \"covert\" to be available in PATH.

This requires songs' directories to be grouped by albums, i.e. one
album per one folder.

The files will be saved to the folder with names like
\"cover_small.jpg\", \"cover_med.jpg\", \"cover_large.jpg\".

You can customize the sizes via the `lyrics-fetcher-small-cover-size'
and `lyrics-fetcher-medium-cover-size' variables.

The behavior of the function is modified by \\[universal-argument] the
same way as `lyrics-fetcher-show-lyrics'." t)
(autoload 'lyrics-fetcher-emms-browser-open-large-cover-at-point "lyrics-fetcher" "\
Open cover_large for the current point in EMMS browser." t)
(register-definition-prefixes "lyrics-fetcher" '("lyrics-fetcher-"))


;;; Generated autoloads from lyrics-fetcher-analyze.el

(autoload 'lyrics-fetcher-analyze-lyrics-count "lyrics-fetcher-analyze" "\
Count top-N words for EMMS tracks at point or region.

\\[universal-argument] sets the level of detalization.  I.e. in
`emms-browse-by-artist', running this function on an artist results in
per-artist summary, running with one argument creates a summary on
each of the artist's albums, and running with two arguments creates a
summary for each track.

Change the `lyrics-fetcher-analyze-top-n' variable to control the
number of words to count.  You may also want to extend
`lyrics-fetcher-analyze-stop-words' if you're running this with a
language other than English." t)
(register-definition-prefixes "lyrics-fetcher-analyze" '("lyrics-fetcher-analyze-"))


;;; Generated autoloads from lyrics-fetcher-genius.el

(register-definition-prefixes "lyrics-fetcher-genius" '("lyrics-fetcher-genius-"))


;;; Generated autoloads from lyrics-fetcher-neteasecloud.el

(register-definition-prefixes "lyrics-fetcher-neteasecloud" '("lyrics-fetcher-neteasecloud-"))

;;; End of scraped data

(provide 'lyrics-fetcher-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lyrics-fetcher-autoloads.el ends here
