#!/bin/bash
# $@ contains: "${bin} -- ${XserverArg}" but all splitted, so $2 may "--"
# but not for sure. $3 is typically ":1" (display) $4 typically "-nolisten"
# and so on. Depending on your config settings.
#
# do something before
#
# Start D-Bus session
#
if command -v dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

export $(dbus-launch)

$HOME/.xsessionrc &> /dev/null # i can transfer the output somewhere else, if i'll need that
startx $@ &> /dev/null
clear
cat $HOME/.config/tbsm/ascii.txt
# do something after
