#!/bin/bash
# $@ contains: "${bin} -- ${XserverArg}" but all splitted, so $2 may "--"
# but not for sure. $3 is typically ":1" (display) $4 typically "-nolisten"
# and so on. Depending on your config settings.
#
# do something before
#
$HOME/.xsessionrc &> /dev/null # i can transfer the output somewhere else, if i'll need that
startx $@ &> /dev/null
clear
cat $HOME/.config/tbsm/ascii.txt
# do something after
